CREATE TABLE IF NOT EXISTS tables (
    id TEXT PRIMARY KEY,
    lang_id INTEGER DEFAULT NULL,
    iso_63901 TEXT NOT NULL,
    iso_63903 TEXT NOT NULL,
    name TEXT NOT NULL,
    local_name TEXT NOT NULL,
    tag TEXT NOT NULL UNIQUE,
    text_direction TEXT NOT NULL DEFAULT 'lt',
    has_audio BOOLEAN NOT NULL DEFAULT 1,
    has_text BOOLEAN NOT NULL DEFAULT 1,
    total_versions INTEGER NOT NULL DEFAULT 1,
    font TEXT DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)