CREATE TABLE IF NOT EXISTS favourites (
   id TEXT PRIMARY KEY,
   song_id TEXT UNIQUE NOT NULL,
   book_id TEXT NOT NULL,
   titles TEXT NOT NULL,
   number INTEGER NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
)