CREATE TABLE IF NOT EXISTS lyrics (
    id TEXT PRIMARY KEY,
    song_id TEXT NOT NULL,
    type TEXT NOT NULL,
    number INTEGER DEFAULT NULL,
    gamme TEXT DEFAULT NULL,
    lines TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (song_id) REFERENCES songs(id) ON DELETE CASCADE
)