CREATE TABLE IF NOT EXISTS songs (
   id TEXT PRIMARY KEY,
   book_id TEXT NOT NULL,
   titles TEXT NOT NULL,
   number INTEGER NOT NULL,
   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
)